# Generated by Django 4.2.19 on 2025-03-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # Task modal migrations with all fields for
    # setting up the tmsapp_task table in the
    # database.
    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('created_on', models.CharField(default='')),
                ('priority', models.CharField(default='', max_length=10)),
                ('started', models.BooleanField(default=True)),
                ('started_on', models.CharField(default='')),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.CharField(default='')),
            ],
        ),
    ]
